# Generated by Django 4.1 on 2022-08-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_customers_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
